# Generated by Django 5.2.5 on 2025-08-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_image_url',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='image_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='team/default.jpg', upload_to='team/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(default='testimonials/default.jpg', upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='therapy',
            name='image',
            field=models.ImageField(default='therapies/default.jpg', upload_to='therapies/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles/'),
        ),
    ]
