# Generated by Django 5.2.5 on 2025-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0003_remove_teammember_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.AlterField(
            model_name='therapy',
            name='image',
            field=models.ImageField(upload_to='therapy/'),
        ),
    ]
