# Generated by Django 5.2.5 on 2025-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0005_alter_article_image_alter_teammember_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTherapyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='family_therapy_articles/')),
                ('reviewer', models.CharField(help_text='Medically reviewed by...', max_length=100)),
            ],
        ),
    ]
