# Generated by Django 5.2.5 on 2025-08-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0006_familytherapyarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_type', models.CharField(choices=[('Individual', 'Individual Therapy'), ('Couples', 'Couples Therapy'), ('Online', 'Online Therapy'), ('Group', 'Group Therapy')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='therapy_articles/')),
                ('reviewer', models.CharField(help_text='Medically reviewed by...', max_length=100)),
            ],
        ),
    ]
