# Generated by Django 5.2.5 on 2025-08-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation_app', '0007_therapyarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('no_of_therapy_day', models.IntegerField()),
                ('family_members_count', models.IntegerField()),
                ('address', models.TextField()),
                ('time_availability', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
